name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: sudo apt-get install libcurl4-openssl-dev
    - name: build
      run: gcc -o htpdate htpdate.c -lcurl
